package meter

// Code generated by github.com/andig/cmd/tools/decorate.go. DO NOT EDIT.

import (
	"github.com/andig/evcc/api"
)

func decorateSMA(base *smaMeter, battery func() (float64, error)) api.Meter {
	switch {
	case battery == nil:
		return base

	case battery != nil:
		return &struct {
			*smaMeter
			api.Battery
		}{
			smaMeter: base,
			Battery: &decorateSMABatteryImpl{
				battery: battery,
			},
		}
	}

	return nil
}

type decorateSMABatteryImpl struct {
	battery func() (float64, error)
}

func (impl *decorateSMABatteryImpl) SoC() (float64, error) {
	return impl.battery()
}
